name: test
on:
  - push
env:
  CI: 'true'
jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - ruby:3.3
          - ruby:3.4
    steps:
      - uses: actions/checkout@v3
      - name: bundle install
        run: |
          gem install bundler -v '~>2.0'
          bundle install --jobs 4 --retry 3
          bundle exec rake bundle:update
          bundle exec rake bundle:check
      - name: Run lint
        run: |
          bundle exec rubocop
